shejiao/urls.py
# -*- coding: utf-8 -*-
#from django.conf.urls.defaults import *
from django.conf.urls import url, include
from django.contrib import admin
from yonghu.feed import RSSRecentNotes,RSSUserRecentNotes
import shejiao, django
import yonghu.views
import django.contrib.syndication.views
import django.views.static
import django.conf.urls
import django.conf.urls.i18n
from django.conf import settings
from django.conf.urls.static import static
import captcha



rss_feeds = {
    'recent': RSSRecentNotes,
}

rss_user_feeds = {
    'recent': RSSUserRecentNotes,
}

urlpatterns = [
    url(r'^index/$',yonghu.views.index),
    url(r'^user/$',yonghu.views.index),
    # url(r'^user/(?P<_username>[a-zA-Z\-_\d]+)/$',tmitter.mvc.views.index_user, name= "tmitter-mvc-views-index_user"),
    # url(r'^user/(?P<_email>[a-zA-Z\-_\-.\-@\d]+)/$',yonghu.views.index_user_page, name= "shejiao-yonghu-views-index_user"),
    url(r'^friends/(?P<_email>[a-zA-Z\-_\-.\-@\d]+)/$',yonghu.views.url_list, name= "shejiao-yonghu-views-url_list"),

    url(r'^users/$',yonghu.views.users_list,name= "yonghu.views.users_list"),
    url(r'^signin/$',yonghu.views.signin, name="signin"),
    url(r'^signout/$',yonghu.views.signout),
    url(r'^signup/$',yonghu.views.signup),
    url(r'^settings/$',yonghu.views.settings, name ='shejiao-yonghu-views-settings'),
    url(r'^edit/$',yonghu.views.edit, name ='shejiao-yonghu-views-edit'),
    url(r'^changepassword/$',yonghu.views.changepassword, name ='shejiao-yonghu-views-changepassword'),
    url(r'^forgetpwd/$', yonghu.views.forgetpwd, name='shejiao-yonghu-views-forgetpwd'),
    url(r'^message/(?P<_id>\d+)/$',yonghu.views.detail, name = "shejiao-yonghu-views-detail"),
    url(r'^message/(?P<_id>\d+)/delete/$',yonghu.views.detail_delete, name = "shejiao-yonghu-views-detail_delete"),
    url(r'^friend/add/(?P<_username>[a-zA-Z\-_\d]+)',yonghu.views.friend_add, name="shejiao-yonghu-views-friend_add"),
    url(r'^friend/remove/(?P<_username>[a-zA-Z\-_\d]+)',yonghu.views.friend_remove, name='shejiao.yonghu.views.friend_remove'),
    url(r'^api/note/add/',yonghu.views.api_note_add),
    # Uncomment this for admin:
    url(r'^admin/',include(admin.site.urls)),
    # url(r'^xadmin/',xadmin.site.urls),
    url(r'^feed/rss/(?P<url>.*)/$', django.contrib.syndication.views.Feed, {'feed_dict': rss_feeds}),
    url(r'^user/feed/rss/(?P<url>.*)/$', django.contrib.syndication.views.Feed, {'feed_dict': rss_user_feeds}),
#    url(r'^statics/(?P<path>.*)$', django.views.static.serve, {'document_root': settings.STATIC_ROOT}),
    url(r'^i18n/', django.conf.urls.i18n.i18n_patterns),
    url(r'^create_code_img/', yonghu.views.create_code_img),
    url(r'^friends/$', yonghu.views.friends , name="shejiao-yonghu-views-friends"),
    url('', include('social_django.urls', namespace='social')),
    url(r'^search/', include('haystack.urls')),
    url(r'^news/$', yonghu.views.news, name="news"),
    url(r'^add/(?P<ids>[a-z\-@\d\s]+)/$', yonghu.views.add, name='add'),
    url(r'^showevent/$', yonghu.views.showevent, name='showevent'),

]

yonghu/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import  models
from django.contrib import admin
from django.utils import timesince, html
from django.utils.encoding import python_2_unicode_compatible
from django.contrib.auth.models import AbstractUser

from tinymce.models import HTMLField
from utils import formatter, function
from shejiao.settings import *
import PIL
from StringIO import StringIO
import six
import time

class Event(models.Model):
    id = models.AutoField(primary_key=True)
    e_name = models.CharField(verbose_name='事件名', max_length=20)
    e_address = models.CharField(verbose_name='事件地址', max_length=50)
    e_balance = models.CharField(verbose_name='余额', max_length=20)
    attr = models.CharField(verbose_name='事件属性', choices=(('col',u'国内大学'),('for',u'国外大学'), ('gam', u'游戏'), ('sta', u'明星'), ('sto', u'股票'), ('boo', u'读书'), ('spo', u'体育'), ('car', u'车'), ('mus', u'音乐'), ('mov', u'电影')),max_length=20, null=True, blank=True)
    # account = models.ManyToManyField(UserProfile,verbose_name='参与用户',blank=True)


    def __unicode__(self):
        return self.e_name

    def addtime_format(self):
        return self.addtime.strftime('%Y-%m-%d %H:%M:%S')

    class Meta:
        verbose_name = u'事件信息'
        verbose_name_plural = u'事件信息'


class EventAdmin(admin.ModelAdmin):
    list_display = ('id', 'e_name', 'e_address', 'e_balance')
    list_display_links = ('e_name',)
    # list_per_page = ADMIN_PAGE_SIZE

    class Meta:
        verbose_name = '事件信息'
        verbose_name_plural = '事件信息'

# category model
@python_2_unicode_compatible
class Category(models.Model):
    name = models.CharField('名称', max_length=20 , default="")

    def __unicode__(self):
        return self.name

    def save(self, **kwargs):
        self.name = self.name[0:20]
        return super(Category, self).save()

    class Meta:
        verbose_name = '分类'
        verbose_name_plural = '分类'

    def __str__(self):
        return "%s | %s | %s" % (
            six.text_type(self.name))


class CategoryAdmin(admin.ModelAdmin):
    list_display = ('id', 'name')
    list_display_links = ('id', 'name')
    list_per_page = ADMIN_PAGE_SIZE
    search_fields = ['name']
    list_filter = ['name']

    class Meta:
        verbose_name = '分类'
        verbose_name_plural = '分类'

# User model
class UserProfile(AbstractUser):
    id = models.AutoField(primary_key=True)

    userip = models.CharField(verbose_name='登录IP', max_length=20, default='', blank=True)
    # username = models.CharField(verbose_name='用户名', max_length=20)
    # password = models.CharField(verbose_name='密码', max_length=100)
    # email = models.EmailField(verbose_name='邮箱')
    gender = models.CharField(verbose_name='性别',choices=(('m',u'男'),('f',u'女')), max_length=5,null=True, blank=True)
    phone = models.CharField(verbose_name='电话', max_length=20, default='', blank=True)
    # area = models.ForeignKey(Area,verbose_name='地区')
    face = models.ImageField(verbose_name='头像', upload_to='face/%Y/%m/%d', default='', blank=True)
    url = models.CharField(verbose_name='个人主页', max_length=200, default='', blank=True)
    about = models.TextField(verbose_name='个性签名', max_length=1000, default='', blank=True)
    addtime = models.DateTimeField(verbose_name='注册时间', auto_now=True)
    friend = models.ManyToManyField("self", verbose_name='朋友')
    associate = models.ManyToManyField(Event, verbose_name='关联事件', max_length=50, blank=True)

    def __unicode__(self):
        return self.username

    def addtime_format(self):
        return self.addtime.strftime('%Y-%m-%d %H:%M:%S')

    # def save(self, modify_pwd=True):
    #     if modify_pwd:
    #         self.password = function.md5_encode(self.password)
    #     self.about = formatter.substr(self.about, 20, True)
    #     super(UserProfile, self).save()

    class Meta:
        verbose_name = u'用户信息'
        verbose_name_plural = u'用户信息'


class UserProfileAdmin(admin.ModelAdmin):
    list_display = ('id', 'username', 'gender', 'email', 'phone','addtime_format')
    list_display_links = ('username','email', 'gender')
    list_per_page = ADMIN_PAGE_SIZE
    search_fields = ['username', 'email']
    list_filter = ['username', 'email']

    class Meta:
        verbose_name = '用户信息'
        verbose_name_plural = '用户信息'


# Note model
class Note(models.Model):
    id = models.AutoField(
        primary_key=True
    )
    message = HTMLField(verbose_name='消息')
    addtime = models.DateTimeField(verbose_name='发布时间', auto_now=True)
    category = models.ForeignKey(Category, verbose_name='来源')
    user = models.ForeignKey(UserProfile, verbose_name='发布者')

    def __unicode__(self):
        return self.message

    def message_short(self):
        return formatter.substr(self.message, 30)

    def addtime_format_admin(self):
        return self.addtime.strftime('%Y-%m-%d %H:%M:%S')

    def category_name(self):
        return self.category.name


    def save(self):
        self.message = formatter.content_tiny_url(self.message)
        self.message = html.escape(self.message)
        self.message = formatter.substr(self.message, 140)
        super(Note, self).save()

    class Meta:
        verbose_name = u'消息'
        verbose_name_plural = u'消息'

    def get_absolute_url(self):
        return APP_DOMAIN + 'message/%s/' % self.id


class NoteAdmin(admin.ModelAdmin):
    list_display = ('id', 'message_short', 'addtime_format_admin', 'category_name')
    # list_display_links = ('id', 'message_short')
    # search_fields = ['message']
    # list_per_page = ADMIN_PAGE_SIZE
    # list_filter = ['user']

    class Meta:
        verbose_name = u'消息'
        verbose_name_plural = u'消息'


admin.site.register(Note, NoteAdmin)
admin.site.register(Category, CategoryAdmin)
admin.site.register(UserProfile, UserProfileAdmin)
admin.site.register(Event, EventAdmin)

templates/account.html
{% extends "base.html" %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% get_available_languages as LANGUAGES %}
{% get_current_language_bidi as LANGUAGE_BIDI %}
{% load user_tags %}
{% block title %}{{ page_title }}{% endblock %}
{% block main %}
<div class="form">
    <div class="message">{{ state.message }}</div>
    <form action="/account/" method="post">
        <table cellpadding="0" cellspacing="0">
            <ul id="nave">
            <li><a href="/changepassword">{% trans 'Change password' %}</a></li>
            <li><a href="/changeemail">{% trans 'Change email' %}</a></li>
            </ul>
        </table>
    </form>
</div>

{% endblock %}

templates/base.html
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% get_available_languages as LANGUAGES %}
{% get_current_language_bidi as LANGUAGE_BIDI %}
{% load staticfiles %}
{% spaceless %}
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE>
<html>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>牛牛 - {% block title %}{% endblock %}</title>
<link rel="shortcut icon" href="{% static 'images/logo.jpg' %}" />
{% block head_link %}{% endblock %}
<link rel="stylesheet" type="text/css" href="{% static 'styles/default.css' %}" media="all" />
{% block styles %}{% endblock %}

<script type="text/javascript" src="{% static 'styles/jq.js' %}"></script>
<script type="text/javascript"> 
$(function() { 
var rWidth = $(document).width() / 230.0;
var rHeight = $(document).height() / 34;
//alert(rHeight+","+ rWidth); 
$(document.body).css("zoom",Math.min(rWidth, rHeight)); 
}); 
$(window).resize(function() { 
//var rWidth = window.screen.availWidth / 200.0;
///var rHeight = window.screen.availHeight / 320.0;
//alert(rHeight+","+ rWidth); 

var rWidth = $(document).width() / 230.0;
var rHeight = $(document).height() / 34;
$(document.body).css("zoom",Math.min(rWidth, rHeight)); 
}); 
</script> 

</head>
<body style="zoom1:3;transform1:scale(3)">

{% block scripts %}{% endblock %}

<div id="container">
    <div id="header">
        <h1><a href="/"><img src="{% static 'images/logo.jpg' %}" alt="SheJiao" />牛牛</a></h1>
        <ul id="nav">
            <li><a href="/index">首页</a></li>
            {% if not islogin %}
            <li><a href="/signin">登录</a></li>
            <li><a href="/signup">注册</a></li>
            {% else %} 
            <li><a href="/friends/">盟友圈</a></li>
                <li><a href="/news">新闻栏</a></li>
            <li><a href="/edit">我</a></li>
            <li><a href="/signout">注销</a></li>
            {% endif %}
        </ul>
    </div>
    <div id="main">
    {% block main %}{% endblock %}
    </div>
    <div id="footer">
        <a>@牛牛</a>
	</div>
</div>
</body>
</html>
{% endspaceless %}

templates/changepassword.html
{% extends "base.html" %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% get_available_languages as LANGUAGES %}
{% get_current_language_bidi as LANGUAGE_BIDI %}
{% load user_tags %}
{% block title %}{{ page_title }}{% endblock %}
{% block main %}  
<div class="form">
    <form action="/changepassword/" method="post">
        <table cellpadding="0" cellspacing="0">
            <div class="fl form-box">
            <h2>修改密码</h2>
                {#                    <input type='hidden' name='csrfmiddlewaretoken' value='mymQDzHWl2REXIfPMg2mJaLqDfaS1sD5' />#}
                <div class="form-group marb20">
                    <label>新&nbsp;密&nbsp;码</label>
                    <input type="password" name="newpassword"  size="12" placeholder="请输入新密码" />
                </div>
                <div class="form-group marb20">
                    <label>确认密码</label>
                    <input type="password" name="confirm"  size="12" placeholder="请确认密码" />
                </div>
                <div class="error" id="jsLoginTips">{{ state.message }}</div>
                <input class="btn btn-blue" id="jsLoginBtn" type="submit" value="提交"/>
        </table>
    </form>
</div>

{% endblock %}

templates/edit.html
{% extends "base.html" %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% get_available_languages as LANGUAGES %}
{% get_current_language_bidi as LANGUAGE_BIDI %}
{% load user_tags %}
{% block title %}{{ page_title }}{% endblock %}
{% block main %}
<div class="form">
    <form action="/edit/" method="get">
        <table cellpadding="0" cellspacing="0">
            <ul id="nave">
                <div class="list">
                    <li><a href="/settings">个人信息</a></li>
                </div>
                <div class="list">
                    <li><a href="/changepassword">修改密码</a></li>
                </div>
                <div class="list">
                    <li><a href="/showevent">参与事件</a></li>
                </div>
            </ul>
        </table>
    </form>
</div>

{% endblock %}

templates/eventinfo.html
<table>
<tr>
    <td>
    <th>事件名称：</th>
    </td>
    <td>
    <th>{{ event.e_name }}</th>
    </td>
</tr>
<tr>
    <td>
    <th>事件地址：</th>
    </td>
    <td>
    <th>{{ event.e_address }}</th>
    </td>
</tr>
<tr>
    <td>
    <th>事件类型：</th>
    </td>
    {% if event.attr == 'mov' %}
        <td>
        <th>电影</th></td>
    {% elif event.attr == 'mus' %}
        <td>
        <th>音乐</th></td>
    {% elif event.attr == 'car' %}
        <td>
        <th>汽车</th></td>
    {% elif event.attr == 'boo' %}
        <td>
        <th>图书</th></td>
    {% elif event.attr == 'gam' %}
        <td>
        <th>游戏</th></td>
    {% elif event.attr == 'for' %}
        <td>
        <th>国外大学</th></td>
    {% elif event.attr == 'col' %}
        <td>
        <th>国内大学</th></td>
    {% elif event.attr == 'spo' %}
        <td>
        <th>体育</th></td>
    {% elif event.attr == 'sta' %}
        <td>
        <th>明星</th></td>
    {% elif event.attr == 'sto' %}
        <td>
        <th>股票</th></td>
    {% endif %}
</tr>
<tr>
    <td>
    <th>事件余额：</th>
    </td>
    <td>
    <th>{{ event.e_balance }}</th>
    </td>
</tr>
<tr>
    <td>
    <th>参与人数：</th>
    </td>
    <td>
    <th>{{ event.userprofile_set.all|length }}</th>
    </td>
</tr>
</table>

templates/forgetpwd.html
{% extends "base.html" %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% get_available_languages as LANGUAGES %}
{% get_current_language_bidi as LANGUAGE_BIDI %}
{% load user_tags %}
{% block title %}{{ page_title }}{% endblock %}
{% block main %}
<div class="form">
    <form action="/forgetpwd/" method="post">
        <table cellpadding="0" cellspacing="0">
            <div class="fl form-box">
            <h2>修改密码</h2>
                {#                    <input type='hidden' name='csrfmiddlewaretoken' value='mymQDzHWl2REXIfPMg2mJaLqDfaS1sD5' />#}
                <div class="form-group marb20">
                    <label>邮&nbsp;&nbsp;&nbsp;箱</label>
                    <input type="text" name="email"  size="20" placeholder="请输入邮箱" />
                </div>
                <div class="form-group marb20">
                    <label>新&nbsp;密&nbsp;码</label>
                    <input type="password" name="newpassword"  size="12" placeholder="请输入新密码" />
                </div>
                <div class="form-group marb20">
                    <label>确认密码</label>
                    <input type="password" name="confirm"  size="12" placeholder="请确认密码" />
                </div>
                <div class="error" id="jsLoginTips">{{ state.message }}</div>
                <input class="btn btn-blue" id="jsLoginBtn" type="submit" value="提交"/>
        </table>
    </form>
</div>

{% endblock %}

templates/index.html
{% extends "base.html" %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% get_available_languages as LANGUAGES %}
{% get_current_language_bidi as LANGUAGE_BIDI %}
{% load user_tags %}
{% block title %}{{ page_title }}{% endblock %}
{% block head_link %}
{#{% if user %}#}
{#<link rel="alternate" type="application/rss+xml" title="{{ user.username }} {% trans ' recent message' %}" href="/user/feed/rss/recent/{{ user.username }}" />#}
{#{% else %}#}
{#<link rel="alternate" type="application/rss+xml" title="{% trans 'Recent message of eveyone' %}" href="/feed/rss/recent/" />#}
{#{% endif %}#}
{% endblock %}

{% block  main %}
    {% include 'include/postform.html' %}
    {% if islogin %}
        {% if self_home %}
            {% include 'include/postform.html' %}
        {% endif %}
    {% endif %}

    <div class="list">
        <ol>
        {% for item in notes.object_list %}
        <li>
            {% include 'include/list_item.html' %}
        </li>
        {% endfor %}
        </ol>
        <div class="pageturn">
            <ul class="pagelist">
            {% if notes.has_previous %}
                <li class="long"><a href="?{{ notes.previous_page_number.querystring }}">上一页</a></li>
            {% endif %}
            {% for page in notes.pages %}
                {% if page %}
                    {% ifequal page notes.number %}
                        <li class="active"><a href="?{{ page.querystring }}">{{ page }}</a></li>
                    {% else %}
                        <li><a href="?{{ page.querystring }}" class="page">{{ page }}</a></li>
                    {% endifequal %}
                {% else %}
                    <li class="none"><a href="">...</a></li>
                {% endif %}
            {% endfor %}
            {% if notes.has_next %}
                <li class="long"><a href="?{{ notes.next_page_number.querystring }}">下一页</a></li>
            {% endif %}
            </ul>
        </div>
    </div>
{% endblock %}

templates/result_message.html
{% extends "base.html" %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% get_available_languages as LANGUAGES %}
{% get_current_language_bidi as LANGUAGE_BIDI %}
{% block title %}{{ page_title }}{% endblock %}
{% block  main %}
<div class="message">{{ message }}</div>
{% if go_back_url %}
<a href="{{ go_back_url }}">返回</a>
{% else %}
<a href="/">返回</a>
{% endif %}
{% endblock %}

templates/settings.html
{% extends "base.html" %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% get_available_languages as LANGUAGES %}
{% get_current_language_bidi as LANGUAGE_BIDI %}
{% load user_tags %}
{% block title %}{{ page_title }}{% endblock %}
{#{% block scripts %}#}
{#    <script>#}
{#        /*#}
{#         自强学堂 学习更多IT技术#}
{#         http://www.ziqiangxuetang.com#}
{#         */#}
{##}
{#        $.ajaxSetup({#}
{#            data: {csrfmiddlewaretoken: '{{ csrf_token }}'},#}
{#        });#}
{##}
{#        function select_drug() {#}
{#            var drug = document.forms[0].drug;#}
{#            var drugs = "";#}
{#            var i;#}
{#            for (i = 0; i < drug.length; i++) {#}
{#                if (drug[i].checked) {#}
{#                    drugs = drugs + drug[i].value + " ";#}
{#                }#}
{#            }#}
{##}
{#            $.post('{% url "exam2014" %}', {'drugs': drugs}, function (ret) {#}
{#                $('#result').html(ret);#}
{#            })#}
{#        }#}
{#    </script>#}
{#{% endblock %}#}
{% block main %}
    <div class="form">
        <form action="{% url 'shejiao-yonghu-views-settings' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <table cellpadding="0" cellspacing="0">
                <div class="fl form-box">
                    <h2>修改个人信息</h2>
                    {#                    <input type='hidden' name='csrfmiddlewaretoken' value='mymQDzHWl2REXIfPMg2mJaLqDfaS1sD5' />#}
                    <img src="{{ user.face|face }}" class="face100" alt="头像"/>
                    <div class="form-group marb20">
                        <label>头&nbsp;&nbsp;&nbsp;像</label>
                        {#                    <img src="{{ user.face|face }}" class="face100" alt="头像" />#}
                        <input type="file" name="face" class="text" size="6"/>
                    </div>
                    <div class="form-group marb20">
                        <label>昵&nbsp;&nbsp;&nbsp;称</label>
                        <input type="text" name="username" value="{{ user.username }}" size="12" placeholder="请输入昵称"/>
                    </div>
                    <div class="form-group marb20">
                        <label>姓&nbsp;&nbsp;&nbsp;别</label>
                        <select name="gender" ,id="sex1">
                            {% ifequal 'm' user.gender %}
                            <option value="m">男</option>
                            <option value="f">女</option>
                            {% else %}
                            <option value="f">女</option>
                            <option value="m">男</option>
                            {% endifequal %}
                        </select>
                    </div>
                    <div class="form-group marb20">
                        <label>个人主页</label>
                        <p1>{{ user.url }}</p1>
                    </div>
                    <div class="form-group marb20">
                        <label>邮&nbsp;&nbsp;&nbsp;箱</label>
                        <input name="email" type="text" value="{{ user.email }}" size="12" placeholder="请输入邮箱"/>
                    </div>
                    <div class="form-group marb20">
                        <label>电&nbsp;&nbsp;&nbsp;话</label>
                        <input name="phone" type="text" value="{{ user.phone}}" size="20" placeholder="请输入电话号码"/>
                    </div>
                    <div class="form-gr">
                        <p>个性签名</p>
                    </div>
                    <div>
                        <textarea name="about" class="text" cols="31" rows="4"
                                  placeholder="自我介绍。。。">{{ user.about }}</textarea>
                    </div>
                    <div class="error" id="jsLoginTips">{{ state.message }}</div>
                    <input class="btn btn-blue" id="jsLoginBtn" type="submit" value="保存 "/>
                </div>
            </table>
        </form>
    </div>
{% endblock %}

templates/show.html
{% extends "base.html" %}
{% load i18n %}
{% load user_tags %}
{% load staticfiles %}
{% block title %}搜索结果{% endblock %}
{% block head_link %}
{% endblock %}
{% block scripts %}
    <script src="http://apps.bdimg.com/libs/html5shiv/3.7/html5shiv.min.js"></script>
    <script src="http://apps.bdimg.com/libs/respond.js/1.4.2/respond.min.js"></script>
{% endblock %}
{% block  main %}
    <div class="list">
        <h>事件列表：</h>
        <ol>
            {% for event in events %}
                <li>
                    <div>
                        {% include 'showinfo.html' %}
                    </div>
                </li>
            {% empty %}
                <p>无事件</p>
            {% endfor %}
        </ol>
    </div>
{% endblock %}

templates/showevents.html
{% extends "base.html" %}
{% load i18n %}
{% load user_tags %}
{% load staticfiles %}
{% block title %}浏览{% endblock %}
{% block head_link %}
{% endblock %}
{% block scripts %}
    <script src="http://apps.bdimg.com/libs/html5shiv/3.7/html5shiv.min.js"></script>
    <script src="http://apps.bdimg.com/libs/respond.js/1.4.2/respond.min.js"></script>
{% endblock %}
{% block  main %}
    <div class="list">
    <h>部分参与事件：共参与{{ user.associate.all|length }}件</h>
        <ol>
            {% for event in user.associate.all|slice:":3" %}
                <li>
                    <div>
                        {% include 'eventinfo.html' %}
                    </div>
                </li>
            {% empty %}
                <p>无参与事件</p>
            {% endfor %}
        </ol>
    </div>
{% endblock %}

templates/signin.html
{% extends "base.html" %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% get_available_languages as LANGUAGES %}
{% get_current_language_bidi as LANGUAGE_BIDI %}
{% block title %}用户登录{% endblock %}
{% block main %}
    <div class="fl form-box">
        <h2>帐号登录</h2>
        <form action="/signin/" method="post">
{#            {% csrf_token %}#}
            <div class="form-group marb20">
                <label>邮&nbsp;&nbsp;&nbsp;箱</label>
                <input name="email" type="text" placeholder="邮箱"/>
            </div>
            <div class="form-group marb8">
                <label>密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码</label>
                <input name="password" type="password" placeholder="请输入您的密码"/>
            </div>
            <div class="error" id="jsLoginTips">{{ state.message }}</div>
            <div class="auto-box marb38">
                {#                        <label><input type="checkbox" id="jsAutoLogin"> 自动登录</label>#}
                <a class="fr" href="{% url 'shejiao-yonghu-views-forgetpwd' %}">忘记密码？</a>
            </div>
            <input class="btn btn-blue" id="jsLoginBtn" type="submit" value="立即登录 > "/>
        </form>
        <p1 class="form-p">没有牛牛帐号？<a href="/signup">[立即注册]</a></p1>
    </div>
{% endblock %}

templates/url.html
{% extends "base.html" %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% get_available_languages as LANGUAGES %}
{% get_current_language_bidi as LANGUAGE_BIDI %}
{% load user_tags %}
{% block title %}{{ page_title }}{% endblock %}
{% block main %}
    <div class="fl form-box">
        <h2>盟友信息</h2>
        {#                    <input type='hidden' name='csrfmiddlewaretoken' value='mymQDzHWl2REXIfPMg2mJaLqDfaS1sD5' />#}
        <img src="{{ user.face|face }}" class="face100" alt="头像"/>
        <div class="form-group marb20">
            <label>昵&nbsp;&nbsp;&nbsp;称</label>
            <p>{{ user.username }}</p>
        </div>
        <div class="form-group marb20">
            <label>姓&nbsp;&nbsp;&nbsp;别</label>
            {% ifequal user.sex 'm' %}
                <p>男</p>
            {% else %}
                <p>女</p>
            {% endifequal %}
        </div>
        <div class="form-group marb20">
            <label>邮&nbsp;&nbsp;&nbsp;箱</label>
            <p>{{ user.email }}</p>
        </div>
        <div class="form-group marb20">
            <label>电&nbsp;&nbsp;&nbsp;话</label>
            <p>{{ user.phone }}</p>
        </div>
        <div class="form-gr">
            <p>个性签名</p>
        </div>
        <p>{{ user.about }}</p>
    </div>
{% endblock %}